apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- blank-repo.yaml
# - dev-flux-config-repo.yaml
- dev2-flux-config-repo.yaml
- kustomize.yaml
- namespace.yaml
- rbac.yaml