apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant
  namespace: flux-system
spec:
  interval: 1m0s
  serviceAccountName: ${TENANT}
  sourceRef:
    kind: GitRepository
    name: ${TENANT}-flux-config
  prune: true
