apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rbac.yaml
- sync.yaml
namespace: flux-system
patches:
- path: kustomize.yaml
  target:
    kind: Kustomization
    annotationSelector: hmcts.github.com/kustomize-defaults != disabled
