---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-team
  namespace: flux-system
spec:
  interval: 1m0s
  include:
    - repository:
        name: flux-system
      fromPath: /apps/flux-system
      toPath: /apps/flux-system
  ref:
    branch: main
  url: https://github.com/endakelly/dev-flux-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-team
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev-team
  sourceRef:
    kind: GitRepository
    name: dev-team
