apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cnp-flux-config
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/endakelly/dev-flux-config