apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 1m0s
  serviceAccountName: tenant-sa
  sourceRef:
    kind: GitRepository
    name: cnp-flux-config
  prune: true
  postBuild:
    substitute:
      TENANT: "cft"