apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-tenant
  namespace: flux-system
spec:
  interval: 1m0s
  serviceAccountName: tenant-sa
  sourceRef:
    kind: GitRepository
    name: dev-flux-config
  prune: true
