apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 1m0s
  serviceAccountName: dev-team
  sourceRef:
    kind: GitRepository
    name: dev-flux-config
  prune: true
  postBuild:
    TENANT: "dev"