apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
- ../../aad-pod-identity
- ../../delete-hung-pods
- ../../external-dns
- ../../hello-kubernetes
- ../../kube-slack
- ../../traefik-crds
- ../../traefik2
