apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/dev/staging/${CLUSTER}
  postBuild:
    substitute:
      ENVIRONMENT: "staging"
      WI_ENVIRONMENT: "staging"
      TENANT: "dev"