apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sds-tenant
  namespace: flux-system
spec:
  interval: 1m0s
  serviceAccountName: tenant-sa
  sourceRef:
    kind: GitRepository
    name: sds-flux-config
  prune: true
