apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev2-team
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/endakelly/dev2-flux-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev2-team
  namespace: flux-system
spec:
  interval: 1m0s
  serviceAccountName: dev2-team
  sourceRef:
    kind: GitRepository
    name: dev2-team
  prune: true
