apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev2-tenant
  namespace: flux-system
spec:
  path: ./dev2/staging
  postBuild:
    substitute:
      ENVIRONMENT: "staging"
      WI_ENVIRONMENT: "staging"
      CLUSTER: "00"
      KEYVAULT_ENVIRONMENT: "staging"
      TENANT: "dev"
