apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/staging/00
  postBuild:
    substitute:
      ENVIRONMENT: "stg"
      WI_ENVIRONMENT: "stg"
      CLUSTER: "00"