apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/staging/00
  sourceRef:
    kind: GitRepository
    name: dev-team
    namespace: dev-team
  postBuild:
    substitute:
      ENVIRONMENT: "stg"
      WI_ENVIRONMENT: "stg"
      CLUSTER: "00"
      GIT_NAMESPACE: "dev-team"
      GIT_REPO: "dev-team"