---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin5
  namespace: flux-system
spec:
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m0s
  path: ./apps/admin5/${ENVIRONMENT}/${CLUSTER}
  postBuild:
    substitute:
      NAMESPACE: "admin5"
      WI_NAME: "admin5"