apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/dev2/staging/00
  postBuild:
    substitute:
      ENVIRONMENT: "staging"
      WI_ENVIRONMENT: "staging"
      CLUSTER: "00"
      TENANT: "dev2"
