apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/sds/sbox/01
  postBuild:
    substitute:
      ENVIRONMENT: "sbox"
      WI_ENVIRONMENT: "sbox"
      CLUSTER: "01"
      TENANT: "sds"
      ENV_MONITOR_CHANNEL: "aks-monitor-sbox"
      WORKLOAD_IDENTITY_ID: "f7c1f6ca-a85f-4a03-8adc-13623bcb1c55"
      ISSUER_URL: "https://uksouth.oic.prod-aks.azure.com/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/8c44a4cc-f514-43fc-bc82-da3bdd3dfacc"

