---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  path: ./tenants/dev/staging
  postBuild:
    substitute:
      ENVIRONMENT: "staging"
      WI_ENVIRONMENT: "staging"
      CLUSTER: "00"
      TENANT: "dev"