---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  path: ./tenants/cft/sbox
  postBuild:
    substitute:
      ENVIRONMENT: "sbox"
      WI_ENVIRONMENT: "sbox"
      CLUSTER: "00"
      TENANT: "cft"