apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cft-tenant
  namespace: flux-system
spec:
  path: ./cft/sbox
  postBuild:
    substitute:
      ENVIRONMENT: "sbox"
      WI_ENVIRONMENT: "sbox"
      CLUSTER: "01"
      KEYVAULT_ENVIRONMENT: "sbox"
      TENANT: "cft"