apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/flux-system
  - ../../base/flux-system/gotk-components.yaml


patches:
  - path: ../../../apps/base/kustomize.yaml
    target:
      kind: Kustomization
      annotationSelector: hmcts.github.com/kustomize-defaults != disabled