apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/flux-system

patches:
- path: kustomize.yaml
  target:
    kind: Kustomization
    annotationSelector: hmcts.github.com/kustomize-defaults != disabled