apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- kustomize.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: kube-system
    target:
      kind: Namespace
      version: v1